option('with-glut',              type : 'string', deprecated: true)
option('egl',                    type : 'feature')
option('gles1',                  type : 'feature')
option('gles2',                  type : 'feature')
option('glut',                   type : 'feature')
option('glvnd',                  type : 'feature')
option('osmesa',                 type : 'feature')
option('libdrm',                 type : 'feature')
option('x11',                    type : 'feature')
option('vulkan',                 type : 'feature')
option('wayland',                type : 'feature')
option('with-system-data-files', type : 'boolean', value : false)
